# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxTodo-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.8'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'
  pod 'M13Checkbox'
  pod 'RxAlertViewable'
  pod 'SDCAlertView'
end
